version: "3.8"

services:
  abiotic-factor:
    image: slymer29/gsh-abiotic-factor:latest
    container_name: gsh-abiotic-factor
    restart: unless-stopped

    ports:
      - "7777:7777/udp"
      - "27015:27015/udp"

    environment:
      GSH_TZ: "Europe/Paris"
      GSH_PUID: "1000"
      GSH_PGID: "1000"

      GSH_SERVER_NAME: "Mon serveur Abiotic Factor"
      GSH_SERVER_PASSWORD: "password"
      GSH_ADMIN_PASSWORD: "changeme"
      GSH_MAX_PLAYERS: "6"
      GSH_WORLD_SAVE_NAME: "Cascade"

      GSH_GAME_PORT: "7777"
      GSH_QUERY_PORT: "27015"

      GSH_STEAM_APP_ID: "2857200"
      GSH_STEAM_USER: "anonymous"
      GSH_STEAM_PASSWORD: ""
      GSH_GAME_UPDATE: "true"
      GSH_VALIDATE_FILES: "true"
      GSH_STEAM_FORCE_PLATFORM: "windows"

      GSH_USE_PERF_THREADS: "true"
      GSH_NO_ASYNC_LOADING_THREAD: "true"
      GSH_LAN_ONLY: "false"
      GSH_PLATFORM_LIMITED: ""
      GSH_MULTIHOME: ""
      GSH_USE_LOCAL_IPS: "false"
      GSH_SANDBOX_INI_PATH: ""
      GSH_ADMIN_INI_PATH: ""

      GSH_USE_WINE: "true"
      GSH_WINEPREFIX: "/opt/wine/abiotic-factor"
      GSH_WINEARCH: "win64"
      GSH_DISPLAY: ":99"
      GSH_XVFB_RESOLUTION: "1024x768x16"

      GSH_SERVER_EXE: "AbioticFactorServer-Win64-Shipping.exe"
      GSH_START_ARGS: ""

    volumes:
      - ./data/server:/opt/games/server
      - ./data/config:/opt/games/config
      - ./data/wine:/opt/wine
      - ./data/steam:/opt/steam
